# Generated by Django 4.2.4 on 2023-11-09 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='website_url',
            field=models.CharField(validators=[django.core.validators.URLValidator]),
        ),
    ]
