# Generated by Django 4.2.4 on 2023-11-09 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_customer_email_alter_customer_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=200, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='website_url',
            field=models.CharField(max_length=200, validators=[django.core.validators.URLValidator]),
        ),
    ]
