# Generated by Django 4.2.6 on 2023-10-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_qwerty2'),
    ]

    operations = [
        migrations.AddField(
            model_name='qwerty2',
            name='alive',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
