# Generated by Django 4.2.4 on 2023-10-31 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_laptop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='operations_system',
            new_name='operation_system',
        ),
    ]
