# Generated by Django 4.2.4 on 2023-11-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_zoodisplayanimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='availability',
            field=models.BooleanField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default=True),
        ),
    ]
