# Generated by Django 4.2.6 on 2023-10-23 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 10, 23), null=True, verbose_name='Start Date'),
        ),
    ]
