# Generated by Django 4.2.4 on 2023-10-26 10:26
from django.db import migrations


def migrate_age_groups(apps, schema_editor):
    person = apps.get_model('main_app', 'Person')
    people = person.objects.all()

    for guy in people:
        if guy.age <= 12:
            guy.age_group = 'Child'
        elif guy.age <= 17:
            guy.age_group = 'Teen'
        else:
            guy.age_group = 'Adult'

    person.objects.bulk_update(people, ['age_group'])


class Migration(migrations.Migration):
    dependencies = [('main_app', '0009_person_alter_course_description')]
    operations = [migrations.RunPython(migrate_age_groups)]
