# Generated by Django 4.2.4 on 2023-10-26 11:35
from django.db import migrations


def change_price(apps, schema_editor):
    phone_model = apps.get_model('main_app', 'Smartphone')
    phones = phone_model.objects.all()

    for phone in phones:
        phone.price = len(phone.brand) * 120

    phone_model.objects.bulk_update(phones, ['price'])


class Migration(migrations.Migration):
    dependencies = [('main_app', '0013_smartphone')]
    operations = [migrations.RunPython(change_price)]
