# Generated by Django 4.2.4 on 2023-10-26 11:35
from django.db import migrations


def change_category(apps, schema_editor):
    phone_model = apps.get_model('main_app', 'Smartphone')
    phones = phone_model.objects.all()

    for phone in phones:
        if phone.price >= 750:
            phone.category = "Expensive"

    phone_model.objects.bulk_update(phones, ['category'])


class Migration(migrations.Migration):
    dependencies = [('main_app', '0014_price_change')]
    operations = [migrations.RunPython(change_category)]
