# Generated by Django 4.2.4 on 2023-10-26 11:54
from django.db import migrations
from datetime import timedelta


def change_status(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')
    orders = order_model.objects.all()

    for order in orders:
        if order.status == "Pending":
            order.delivery = order.order_date + timedelta(days=3)
        elif order.status == "Completed":
            order.warranty = "24 months"
        elif order.status == "Cancelled":
            order_model.objects.filter(id=order.id).delete()


class Migration(migrations.Migration):
    dependencies = [('main_app', '0016_order')]
    operations = [migrations.RunPython(change_status)]
